### ISSUE TITLE
Cannot start service server: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by valdecircarvalho** [BraintoByte/Megaton#2]
I'm receiving the following error.
NVVIDIA-SMI is working fine. 
```
`docker-compose up -d
Creating network "megaton_default" with the default driver
Creating megaton_server_1 ... error

ERROR: for megaton_server_1  Cannot start service server: could not select device driver "nvidia" with capabilities: [[gpu]]

ERROR: for server  Cannot start service server: could not select device driver "nvidia" with capabilities: [[gpu]]
ERROR: Encountered errors while bringing up the project.`
```

**Comment by BraintoByte** [comment]
very good catch, I am adding it to the readme, you need to install nvidia-container-toolkit, I totally forgot

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by BraintoByte** [comment]
when you install it re run it, let me know if it works and I ll close the issue

**Comment by BraintoByte** [comment]
@valdecircarvalho did you solve the issue? other people had the same and fixed it with the toolkit, I am closing the issue if you didn't feel free to reopen it again or open a new one
